"""Generate small display-model TypeScript declarations from Pydantic schemas."""

import json


def schema_type(schema: dict) -> str:
    """Translate only the JSON Schema shapes used by the canonical wire models."""
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[-1]
    if "const" in schema:
        return json.dumps(schema["const"])
    if "enum" in schema:
        return " | ".join(json.dumps(value) for value in schema["enum"])
    for key in ("anyOf", "oneOf"):
        if key in schema:
            return " | ".join(schema_type(part) for part in schema[key])
    kind = schema.get("type")
    if kind == "array":
        if "prefixItems" in schema:
            return "[" + ", ".join(map(schema_type, schema["prefixItems"])) + "]"
        return f"({schema_type(schema['items'])})[]"
    if kind == "object" and isinstance(schema.get("additionalProperties"), dict):
        return f"Record<string, {schema_type(schema['additionalProperties'])}>"
    primitives = {
        "string": "string",
        "integer": "number",
        "number": "number",
        "boolean": "boolean",
        "null": "null",
    }
    if kind in primitives:
        return primitives[kind]
    raise ValueError(f"Unsupported schema shape in client type generator: {schema}")


def typescript_contract(schema: dict) -> str:
    """Generate named models and optional fields; fail on unsupported additions."""
    lines = [
        "// Generated by backend/export_contract.py. Do not edit by hand.",
        "// WGS84 display coordinates; timestamps use ISO 8601 with a timezone.",
    ]
    models = {**schema.get("$defs", {}), schema["title"]: schema}
    for name, model in models.items():
        lines.extend(["", f"export interface {name} {{"])
        required = model.get("required", [])
        for field, definition in model["properties"].items():
            optional = "" if field in required else "?"
            lines.append(f"  {field}{optional}: {schema_type(definition)};")
        lines.append("}")
    return "\n".join(lines) + "\n"
