// Generated by backend/export_contract.py. Do not edit by hand.
// WGS84 display coordinates; timestamps use ISO 8601 with a timezone.

export interface AddressPlace {
  id: string;
  name: string;
  lon: number;
  lat: number;
}

export interface AddressSearchResponse {
  places?: (AddressPlace)[];
  status?: "available" | "unavailable";
  attribution?: string;
}
