// Generated by backend/export_contract.py. Do not edit by hand.
// WGS84 display coordinates; timestamps use ISO 8601 with a timezone.

export interface Provenance {
  provider: string;
  source_url?: string | null;
  attribution: string;
  licence: string;
  fixture: boolean;
  observed_at?: string | null;
  retrieved_at?: string | null;
}

export interface ShadeMetadata {
  requested_time: string;
  effective_time: string;
  geometry_version: string;
  resolution_m: number;
}

export type ShadeState = 0 | 1 | 2 | 3;

export interface TripComparison {
  status: string;
  winner?: string | null;
  route_statuses: Record<string, string>;
  metrics?: Record<string, Record<string, unknown>>;
  scores?: Record<string, number>;
  contributions?: Record<string, Record<string, number>>;
  reasons?: Record<string, (string)[]>;
  manual_choices?: (string)[];
  explanation?: string;
  transit_status?: "unavailable";
}

export interface WalkingEvidence {
  id: string;
  distance_metres: number;
  shaded_metres: number;
  unshaded_metres: number;
  unknown_metres: number;
  planned_stop_minutes?: number;
  access_state?: "checked_open" | "confirmed_blocked" | "unknown";
  inside_calculation_coverage?: boolean;
  construction_caution?: boolean;
  shade_state?: "current" | "stale" | "failed" | "unknown";
  shade_time_matches_request?: boolean;
  shade_geometry_matches_request?: boolean;
  duration_complete?: boolean;
  water?: WaterEvidence;
  provenance?: Provenance | null;
  samples?: (WalkingShadeSample)[];
  sampled_speed_m_per_s?: number | null;
  sampled_distance_metres?: number | null;
  sampled_stop_minutes?: number | null;
}

export interface WalkingShadeSample {
  start_metres: number;
  end_metres: number;
  requested_time: string;
  metadata?: ShadeMetadata | null;
  state?: ShadeState;
  model?: string;
  explanation: string;
}

export interface WaterEvidence {
  state?: string;
  evidence_complete?: boolean;
  age_hours?: number | null;
  drinking?: boolean | null;
  accessible?: boolean | null;
  operational?: boolean | null;
  extra_distance_metres?: number | null;
  extra_distance_included?: boolean;
  provenance?: Provenance | null;
}

export interface WalkingStop {
  at_metres: number;
  minutes: number;
}

export interface ComparisonRequest {
  departure_time: string;
  stops?: Record<string, (WalkingStop)[]>;
}

export interface ComparisonPreferences {
  weights?: Record<string, number> | null;
  extra_time_limit_minutes?: 5 | null;
}

export interface ComparisonJob {
  id: string;
  status: "running" | "ready" | "failed";
  departure_time: string;
  completed_samples?: number;
  total_samples?: number;
  evidence?: (WalkingEvidence)[];
  choices?: Record<string, TripComparison>;
  explanation: string;
}
