// Generated by backend/export_contract.py. Do not edit by hand.
// WGS84 display coordinates; timestamps use ISO 8601 with a timezone.

export interface ConstructionSite {
  id: string;
  project_id: string;
  starts_on: string;
  ends_on: string;
  geometry: PolygonGeometry;
}

export interface PolygonGeometry {
  type: "Polygon";
  coordinates: (([number, number])[])[];
}

export interface Provenance {
  provider: string;
  source_url?: string | null;
  attribution: string;
  licence: string;
  fixture: boolean;
  observed_at?: string | null;
  retrieved_at?: string | null;
}

export interface ConstructionSnapshot {
  sites?: (ConstructionSite)[];
  availability?: "current" | "stale" | "missing" | "unknown" | "unsupported";
  covers_from?: string | null;
  provenance?: Provenance | null;
}
