// Generated by backend/export_contract.py. Do not edit by hand.
// WGS84 display coordinates; timestamps use ISO 8601 with a timezone.

export interface ForecastHour {
  valid_time: string;
  temperature_c: number | null;
}

export interface Provenance {
  provider: string;
  source_url?: string | null;
  attribution: string;
  licence: string;
  fixture: boolean;
  observed_at?: string | null;
  retrieved_at?: string | null;
}

export interface PaletteForecast {
  days: Record<string, number>;
  hours?: (ForecastHour)[];
  availability: "current" | "stale" | "missing" | "unknown" | "unsupported";
  provenance?: Provenance | null;
}
