// Generated by backend/export_contract.py. Do not edit by hand.
// WGS84 display coordinates; timestamps use ISO 8601 with a timezone.

export interface LineGeometry {
  type: "LineString";
  coordinates: ([number, number])[];
}

export interface MapFeature {
  id: string;
  label: string;
  kind: "observation" | "fountain" | "shade" | "route" | "rest";
  geometry: PointGeometry | LineGeometry | PolygonGeometry;
  availability: "current" | "stale" | "missing" | "unknown" | "unsupported";
  explanation: string;
  provenance: Provenance;
  value?: number | null;
  unit?: string | null;
  drinking_water?: "yes" | "no" | "unknown" | null;
  shade?: ShadeMetadata | null;
  route?: RouteMetrics | null;
  pet?: PetRouteMetrics | null;
  rest_type?: "bench" | "park" | "indoor" | null;
  opening_hours?: string | null;
}

export interface MapLayer {
  id: string;
  label: string;
  kind: "observation" | "fountain" | "shade" | "route" | "rest";
  availability: "current" | "stale" | "missing" | "unknown" | "unsupported";
  explanation: string;
  features: (MapFeature)[];
}

export interface PetRouteMetrics {
  availability: "current" | "stale" | "missing" | "unknown" | "unsupported";
  scenario: string;
  resolution_m: number;
  known_distance_m: number;
  unknown_distance_m: number;
  class_distances_m: Record<string, number>;
  provenance: Provenance;
}

export interface PointGeometry {
  type: "Point";
  coordinates: [number, number];
}

export interface PolygonGeometry {
  type: "Polygon";
  coordinates: (([number, number])[])[];
}

export interface Provenance {
  provider: string;
  source_url?: string | null;
  attribution: string;
  licence: string;
  fixture: boolean;
  observed_at?: string | null;
  retrieved_at?: string | null;
}

export interface RouteMetrics {
  distance_m: number;
  duration_s: number;
}

export interface ShadeMetadata {
  requested_time: string;
  effective_time: string;
  geometry_version: string;
  resolution_m: number;
}

export interface MapSnapshot {
  generated_at: string;
  layers: (MapLayer)[];
  mode?: "fixture" | "online" | "offline";
}
