// Generated by backend/export_contract.py. Do not edit by hand.
// LV95 (EPSG:2056) processing metres; timestamps use ISO 8601 with a timezone.

export interface ShadeCounts {
  unknown: number;
  sunlit: number;
  shaded: number;
  night: number;
}

export interface ShadeMetadata {
  requested_time: string;
  effective_time: string;
  geometry_version: string;
  resolution_m: number;
}

export interface ShadeRequest {
  bounds: [number, number, number, number];
  requested_time: string;
  corridor?: ([number, number])[] | null;
  corridor_width_m?: number;
}

export interface ShadeResponse {
  bounds: [number, number, number, number];
  crs?: "EPSG:2056";
  width: number;
  height: number;
  encoding?: "base64-uint8-row-major-north-first";
  states: string;
  counts: ShadeCounts;
  shade: ShadeMetadata;
  availability: "approximate" | "unknown" | "unsupported";
  model?: "survey-raytrace" | "building-shadow-approximation";
  explanation: string;
}
