// Generated by backend/export_contract.py. Do not edit by hand.
// WGS84 display coordinates; timestamps use ISO 8601 with a timezone.

export interface WalkingRouteRequest {
  start: [number, number];
  end: [number, number];
  mode?: "fixture" | "online" | "offline";
}
